import { browser, expect, $ } from "@wdio/globals";
import { describe, it, beforeEach } from "mocha";
import { obsidianPage } from "wdio-obsidian-service";

const PLUGIN_ID = "obsidian-agent-sandbox";

describe("Plugin loads", function () {
	beforeEach(async function () {
		await obsidianPage.resetVault();
	});

	it("is enabled in the test vault", async function () {
		const loaded = await browser.executeObsidian(({ app }) => {
			return (
				app as unknown as { plugins: { enabledPlugins: Set<string> } }
			).plugins.enabledPlugins.has("obsidian-agent-sandbox");
		});
		expect(loaded).toBe(true);
	});

	it("adds the ribbon icon", async function () {
		// Obsidian sets aria-label from the ribbon title
		const ribbon = $('.side-dock-ribbon-action[aria-label="Open Sandbox Terminal"]');
		await expect(ribbon).toExist();
	});

	it("adds the container status bar item", async function () {
		// The plugin creates status bar items via addStatusBarItem().
		// Wait for them to render — Obsidian may delay status bar initialization.
		const statusBar = $(".status-bar");
		await statusBar.waitForExist({ timeout: 10000 });
	});

	it("registers all expected commands", async function () {
		const commandIds = await browser.executeObsidian(({ app }, pluginId) => {
			const commands = (app as unknown as { commands: { commands: Record<string, unknown> } })
				.commands.commands;
			return Object.keys(commands).filter((id) => id.startsWith(`${pluginId}:`));
		}, PLUGIN_ID);

		// Spot-check key commands — the plugin registers 9 total (see main.ts onload)
		expect(commandIds).toContain(`${PLUGIN_ID}:open-claude-terminal`);
		expect(commandIds).toContain(`${PLUGIN_ID}:sandbox-start-container`);
		expect(commandIds).toContain(`${PLUGIN_ID}:sandbox-stop-container`);
		expect(commandIds).toContain(`${PLUGIN_ID}:sandbox-toggle-firewall`);
		expect(commandIds).toContain(`${PLUGIN_ID}:sandbox-toggle-mcp`);
	});
});

describe("Settings UI", function () {
	beforeEach(async function () {
		await obsidianPage.resetVault();
	});

	it("has four tabs: General, Terminal, Advanced, MCP", async function () {
		await browser.executeObsidianCommand("app:open-settings");

		// Navigate to our plugin's settings tab (vertical tab list on left of settings modal)
		const pluginTab = $(".vertical-tab-nav-item*=Agent Sandbox");
		await expect(pluginTab).toExist();
		await pluginTab.click();

		// Our internal tab bar is rendered inside the settings content area
		for (const label of ["General", "Terminal", "Advanced", "MCP"]) {
			await expect($(`.sandbox-settings-tab=${label}`)).toBeDisplayed();
		}
	});

	it("MCP tab shows permission tier toggles", async function () {
		await browser.executeObsidianCommand("app:open-settings");
		await $(".vertical-tab-nav-item*=Agent Sandbox").click();
		await $(".sandbox-settings-tab=MCP").click();

		// Each tier is rendered as a Setting with the tier name
		for (const tier of ["Read", "Write (scoped)", "Write (vault-wide)", "Navigate", "Manage"]) {
			await expect($(`.setting-item-name=${tier}`)).toBeDisplayed();
		}
	});

	it("auto-generates an MCP token on first load", async function () {
		const token = await browser.executeObsidian(({ app }) => {
			const plugins = (
				app as unknown as {
					plugins: { plugins: Record<string, { settings: { mcpToken: string } }> };
				}
			).plugins.plugins;
			return plugins["obsidian-agent-sandbox"]?.settings?.mcpToken ?? "";
		});
		// 32-char hex string generated by generateToken()
		expect(token).toMatch(/^[a-f0-9]{32}$/);
	});
});

describe("Container status (no Docker required)", function () {
	it("plugin survives without Docker configured", async function () {
		// With no Docker compose path configured, probeStatus will fail
		// gracefully. Verify the plugin didn't crash by checking it's
		// still enabled and responsive.
		const loaded = await browser.executeObsidian(({ app }) => {
			return (
				app as unknown as { plugins: { enabledPlugins: Set<string> } }
			).plugins.enabledPlugins.has("obsidian-agent-sandbox");
		});
		expect(loaded).toBe(true);
	});
});
